# -*- coding: utf-8 -*-
"""sreehari_task6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13ty0NDvYRNYPB6EtMinJlbqmlR1SlTQh
"""

from keras.applications.vgg16 import VGG16
from tensorflow.keras.datasets import cifar10
from tensorflow.keras import datasets, layers, models
from keras.layers import GlobalAveragePooling2D, Dense
from keras.layers import BatchNormalization, Dropout
from keras.models import Model

(x_train, y_train), (x_test, y_test) = datasets.cifar10.load_data()
cifar10_classes = ['airplane', 'automobile', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck']

x_train = x_train/255.0
x_test = x_test/255.0

vgg = VGG16(weights ='imagenet', include_top = False, 
               input_shape =(32,32, 3)) 
vgg.trainable = False
               
x = vgg.output
x = GlobalAveragePooling2D()(x)
x = BatchNormalization()(x)
x = Dropout(0.5)(x) 
x = Dense(512, activation ='relu')(x)
x = BatchNormalization()(x)
x = Dropout(0.5)(x)
x = Dense(10, activation ='softmax')(x)

model = Model(vgg.input, x)
model.compile(optimizer ='Adam', 
              loss ='sparse_categorical_crossentropy', 
              metrics ='accuracy') 

model.fit(x_train, y_train, epochs = 5, validation_data = (x_test, y_test))
test_loss, test_accuracy = model.evaluate(x_test, y_test)
print("Test accuracy: {}".format(test_accuracy))

